### ISSUE TITLE
Move Server Files to the Root Directory in the Repository

### ISSUE THREAD

**Issue by Steve0Greatness** [GenericProgrammer1234/Intweb#3]
I'm not sure why they're not on the Root directory, as of currently, but they really should be.

**Comment by GenericProgrammer1234** [comment]
No. This way the server code can be in the Intweb directory and the README, LICENSE, other stuff. That can be in the root directory.

**Comment by GenericProgrammer1234** [comment]
No. This way the server code can be in the Intweb directory and the README, LICENSE, other stuff. That can be in the root directory.

**Comment by Steve0Greatness** [comment]
> No. This way the server code can be in the Intweb directory and the README, LICENSE, other stuff. That can be in the root directory.

If you don't mind me asking, how is that bad?

**Comment by GenericProgrammer1234** [comment]
Organization.
